version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "09:00"
  groups:
    cargo-dependencies:
      patterns:
        - "*"
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "09:00"
  groups:
    github-actions-dependencies:
      patterns:
        - "*"
  open-pull-requests-limit: 99
