version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: monthly
    day: friday
    time: "09:00"
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    day: friday
    time: "09:00"
  open-pull-requests-limit: 99
