version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  versioning-strategy: auto
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/Berlin
  commit-message:
    prefix: "chore"
  cooldown:
    default-days: 14
  groups:
    cargo:
      patterns:
        - "*"
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: Europe/Berlin
  commit-message:
    prefix: "chore"
  cooldown:
    default-days: 14
  groups:
    github-actions:
      patterns:
        - "*"
  open-pull-requests-limit: 99
