version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "09:00"
    timezone: Europe/Berlin
  commit-message:
    prefix: "chore"
  groups:
    cargo:
      patterns:
        - "*"
  open-pull-requests-limit: 99
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "09:00"
    timezone: Europe/Berlin
  commit-message:
    prefix: "chore"
  groups:
    github-actions:
      patterns:
        - "*"
  open-pull-requests-limit: 99
