name: Nightly checks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * MON-FRI' # 06:00 AM UTC from Monday through Friday

jobs:
  udeps:
    name: Check for unused dependencies
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: |
          echo "RUST_TOOLCHAIN_NIGHTLY=$(just rust-nightly-version)" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_NIGHTLY }}
      - name: Cargo Install
        run: cargo install cargo-udeps
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: debug-build-nightly
      - run: make udeps
