name: Nightly checks
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * MON-FRI' # 06:00 AM UTC from Monday through Friday

jobs:
  udeps:
    name: Check for unused dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly-2022-09-22
          override: true
      - run: cargo install cargo-udeps
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: debug-build-nightly
      - run: make udeps
